
export const EQUIPMENT = [
  // Auras
  { type: "Aura", name: "Baryon Flood Generator", cost: "2,000,000", desc: "Generates a Drone Aura in a sector. It can be toggled to produce either a positive or negative aura, or can be deactivated." },
  { type: "Aura", name: "Energy Dampening Field", cost: "2,000,000", desc: "Generates a Visibility Aura in a sector. It can be toggled to produce either a positive or negative aura, or can be deactivated." },
  { type: "Aura", name: "Gravitron Disruption Field", cost: "2,000,000", desc: "Generates a Damage Aura in a sector. It can be activated or deactivated." },
  { type: "Aura", name: "Interdiction Field", cost: "2,000,000", desc: "Produces Movement Aura effect. It can be activated or deactivated." },
  { type: "Aura", name: "Ion Stream Emitter", cost: "2,000,000", desc: "Generates a Repair Aura in a sector. It can be toggled to produce either a positive or negative aura, or can be deactivated." },
  { type: "Aura", name: "Positron Collection System", cost: "2,000,000", desc: "Generates a Power Aura in a sector. It can be toggled to produce either a positive or negative aura, or can be deactivated." },
  { type: "Aura", name: "Radiation Pulse Emitter", cost: "2,000,000", desc: "Produces an Accuracy Aura. It can be toggled to produce either a positive or negative aura, or can be deactivated." },
  { type: "Aura", name: "Subspace Anchor Field", cost: "2,000,000", desc: "Produces a Jump Aura in the sector. It can be activated or deactivated." },
  
  // Defensive
  { type: "Defensive", name: "Ablative Armor", cost: "2,000,000", desc: "Decreases overall effectiveness of Particle-Class weapons used against the ship by 25%." },
  { type: "Defensive", name: "Active Defense Grid", cost: "15,000,000", desc: "Reduces damage dealt to your ship from Rocket weapons by 50%." },
  { type: "Defensive", name: "Angled Armor Plating", cost: "17,500,000", desc: "Reduces damage dealt to your ship from Torpedo weapons by 50%." },
  { type: "Defensive", name: "Concussive Dampener", cost: "2,000,000", desc: "Decreases overall effectiveness of Concussive-Class weapons used against the ship by 25%." },
  { type: "Defensive", name: "Force Deflector Shields", cost: "17,500,000", desc: "Reduces damage dealt to your ship from Cannon weapons by 50%." },
  { type: "Defensive", name: "Overflow Shields", cost: "15,000,000", desc: "Reduces damage dealt to your ship from Fusion weapons by 50%." },
  { type: "Defensive", name: "Refractive Shields", cost: "2,000,000", desc: "Decreases overall effectiveness of Energy-Class weapons used against the ship by 25%." },
  { type: "Defensive", name: "Structural Integrity Field Generator", cost: "2,000,000", desc: "Protects against critical hits. 50% chance the critical hit will be dissipated and do normal damage instead." },
  
  // Miscellaneous
  { type: "Miscellaneous", name: "Cloaking Device", cost: "5,000,000 * Ship Size", desc: "Subtracts 100 from sector Visibility. Adds 100 to Initiative checks if undetected. Takes 20x ship size in Power to activate." },
  { type: "Miscellaneous", name: "Drone Transponder", cost: "5,000,000 * Ship Size", desc: "50% chance to avoid attacks from dropped enemy Drones." },
  { type: "Miscellaneous", name: "Extended Ammunition Rack", cost: "12,500,000", desc: "Increases the amount of Secondary Weapon ammunition by 50% (effectively +1,000 per secondary hardpoint)." },
  { type: "Miscellaneous", name: "Scanners", cost: "1,000,000", desc: "Adds 25 to scan checks. Allows scanning adjacent sectors for 5 Power." },
  { type: "Miscellaneous", name: "Signature Dampener", cost: "5,000,000", desc: "Doubles your signature difficulty when being viewed by Signature Scanners." },
  { type: "Miscellaneous", name: "Signature Scanners", cost: "10,000,000", desc: "Allows you to detect and plot out the ion and particle trails generated by the passage of starships." },
  { type: "Miscellaneous", name: "Spatial Rift Generator", cost: "2,000,000", desc: "Negates the effects of a Subspace Anchor Field or Interdiction Field. Provides +10 bonus to Initiative." },
  { type: "Miscellaneous", name: "Subspace Jump Drive", cost: "2,500,000 * Ship Size", desc: "Allows you to move to any sector within the same system for 5 Power per ship size and 20 Turns." },
  
  // Offensive
  { type: "Offensive", name: "Advanced Homing", cost: "20,000,000", desc: "Increases the accuracy of Missile secondaries by 20." },
  { type: "Offensive", name: "Advanced Reprogramming Module", cost: "7,500,000", desc: "Improves ship's onboard AI management system, allowing you to reprogram 20 drones per turn. Also allows auto-reprogramming during combat." },
  { type: "Offensive", name: "Armor-Piercing Warheads", cost: "25,000,000", desc: "Increases Torpedo weapons minimum damage by 50." },
  { type: "Offensive", name: "Beam Regulators", cost: "25,000,000", desc: "Beam weapons use 40% less Power upon firing." },
  { type: "Offensive", name: "Grooved Slugs", cost: "15,000,000", desc: "Projectile weapons: +20 Accuracy, +10% Critical Percentage, +20 Armor Integrity negation." },
  { type: "Offensive", name: "Harmonic Amplifiers", cost: "20,000,000", desc: "Increases shield and drone damage by 50% for Flux and EMP weapons (not EMP damage)." },
  { type: "Offensive", name: "Mass Driver", cost: "20,000,000", desc: "Concussion-Class weapons receive a 25% bonus to damage ranges." },
  { type: "Offensive", name: "Particle Accelerator", cost: "20,000,000", desc: "Particle-Class weapons receive a 25% bonus to damage ranges." },
  { type: "Offensive", name: "Positron Gap Generator", cost: "15,000,000", desc: "Drains Power from defending ship equal to 50% of the EMP damage that would have been dealt when blocked by shields." },
  { type: "Offensive", name: "Proximity Warheads", cost: "25,000,000", desc: "Increases the accuracy of Rocket secondaries by 10 and deal twice normal damage." },
  { type: "Offensive", name: "Shaped Charges", cost: "25,000,000", desc: "Increases critical hit percentage for Fusion weaponry by 10. Enables Massive Critical Hits." },
  { type: "Offensive", name: "Singularity Generator", cost: "20,000,000", desc: "Increases critical hit percentage for Plasma weapons by 10 and doubles the critical hit multiplier." },
  { type: "Offensive", name: "Tetra Shells", cost: "10,000,000", desc: "The minimum Drone damage on Flak weapons is increased by +40." },
  { type: "Offensive", name: "Trimedadine Laser Lenses", cost: "25,000,000", desc: "Triples all damage from Laser based weapons." },
  { type: "Offensive", name: "Wave Intensifier", cost: "20,000,000", desc: "Energy-Class weapons receive a 25% bonus to damage ranges." },
  
  // Repair & Resource
  { type: "Repair", name: "Energy Transfer Module", cost: "1,000,000", desc: "Allows you to recharge another ship's Shields and Power at the same rate you repair armor with Repair Drones." },
  { type: "Repair", name: "External Repair Module", cost: "2,000,000 * Ship Size", desc: "Each repair drone can repair an additional 2 Armor." },
  { type: "Repair", name: "Internal Repair Module", cost: "25,000,000 * Ship Size", desc: "Automatically repair at 1/2 rate during actions. Adds +25 to Power, Shields, Armor, and EMP repair/recharge rates. Built-in Energy to Shields Transfer." },
  { type: "Resourcing", name: "External Resourcing Module", cost: "2,500,000 * Ship Size", desc: "Adds +25 to your Resourcing rate and an additional +5 times your ship size." },
  { type: "Resourcing", name: "Improved Processing Module", cost: "1,000,000", desc: "Increases Resourcing rate for each resource drone by 2 units per turn." },
  { type: "Resourcing", name: "Micro Extractor Module", cost: "5,000,000", desc: "Converts 3 units of Ore into 1 unit of Crystal." },
  { type: "Resourcing", name: "Micro Factory Module", cost: "5,000,000", desc: "Converts every 2 units of Precious Metals to 1 unit of Machinery." },
  { type: "Resourcing", name: "Micro Purifier Module", cost: "3,000,000", desc: "Converts 2 units of Ore into 1 unit of Precious Metals." },
  { type: "Resourcing", name: "Micro Refinery Module", cost: "2,500,000", desc: "Converts every 2 units of Fuel to 1 unit of Chemicals." },
  { type: "Resourcing", name: "Resource Scanners", cost: "7,500,000", desc: "Allows you to find new goods in resourceable sectors by using turns." }
];
